<?php
/**
 * Declaration:
 * @param: $value
 * @return: mixed
 * @Author: Loffin
 * Date&Time: 2018/9/3-上午8:42
 */
namespace app\api\model;

use think\Model;
class Cate extends Model
{
    protected $resultSetType = 'cate_name';
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}