<?php
/**
 * Declaration:
 * @param: $value
 * @return: mixed
 * @Author: Loffin
 * Date&Time: 2018/9/3-下午5:38
 */
namespace app\api\model;

use think\Model;
class Orders extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}