<?php
/**
 * Declaration:
 * @param: $value
 * @return: mixed
 * @Author: Loffin
 * Date&Time: 2018/9/3-上午9:10
 */
namespace app\api\model;

use think\Model;
class Weight extends Model
{
    protected $resultSetType = 'weight';
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}